[package]
name = "mint1563"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.18.0", features = ["auto-initialize"] }
chrono = "0.4.39"
iced = { version = "0.13.1", features = ["canvas", "tokio", "debug"] }
iced_native = "0.10.3"
tracing-subscriber = "0.3"
